// <auto-generated />
using System;
using AdessoTurkey.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdessoTurkey.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117180629_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawerFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGroups")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrawDate")
                        .HasDatabaseName("IX_Draws_DrawDate");

                    b.ToTable("Draws", (string)null);
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.DrawGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DrawId");

                    b.ToTable("DrawGroups");
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.DrawTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("DrawGroupId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_DrawTeams_DrawGroupId_TeamId");

                    b.ToTable("DrawTeams", (string)null);
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_Teams_Country");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_Name");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.DrawGroup", b =>
                {
                    b.HasOne("AdessoTurkey.Domain.Entities.Draw", "Draw")
                        .WithMany("Groups")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draw");
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.DrawTeam", b =>
                {
                    b.HasOne("AdessoTurkey.Domain.Entities.DrawGroup", "DrawGroup")
                        .WithMany("Teams")
                        .HasForeignKey("DrawGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdessoTurkey.Domain.Entities.Team", "Team")
                        .WithMany("DrawTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrawGroup");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.Draw", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.DrawGroup", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AdessoTurkey.Domain.Entities.Team", b =>
                {
                    b.Navigation("DrawTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
